extends Node

const MATERIALS = {
	"badguy_black1" : preload("res://materials/badguy_black1.tres"),
	"sdmg_badguy_black1": preload("res://materials/smdg_badguy_black.tres"),
	"father_white1" : preload("res://materials/father_white1.tres"),
	"lw_blue1" : preload("res://materials/lw_blue1.tres"),
	"lw_blue1_pulse" : preload("res://materials/lw_blue1_pulse.tres"),
	"slw_blue1" : preload("res://materials/slw_blue1.tres"),
	"slw_blue1_pulse" : preload("res://materials/slw_blue1_pulse.tres"),
	"radarup_slw_blue1" : preload("res://materials/radarup_slw_blue1.tres"),
	"radarlo_slw_blue1" : preload("res://materials/radarlo_slw_blue1.tres"),
	"lw_orange1" : preload("res://materials/lw_orange1.tres"),
	"lw_orange1_pulse" : preload("res://materials/lw_orange1_pulse.tres"),
	"slw_orange1" : preload("res://materials/slw_orange1.tres"),
	"slw_orange1_pulse" : preload("res://materials/slw_orange1_pulse.tres"),
	"radarup_slw_orange1" : preload("res://materials/radarup_slw_orange1.tres"),
	"radarlo_slw_orange1" : preload("res://materials/radarlo_slw_orange1.tres"),
	"lw_yellow1" : preload("res://materials/lw_yellow1.tres"),
	"lw_yellow1_pulse" : preload("res://materials/lw_yellow1_pulse.tres"),
	"slw_yellow1" : preload("res://materials/slw_yellow1.tres"),
	"slw_yellow1_pulse" : preload("res://materials/slw_yellow1_pulse.tres"),
	"lw_green1" : preload("res://materials/lw_green1.tres"),
	"lw_green1_pulse" : preload("res://materials/lw_green1_pulse.tres"),
	"slw_green1" : preload("res://materials/slw_green1.tres"),
	"slw_green1_pulse" : preload("res://materials/slw_green1_pulse.tres"),
	"radarup_slw_green1" : preload("res://materials/radarup_slw_green1.tres"),
	"radarlo_slw_green1" : preload("res://materials/radarlo_slw_green1.tres"),
	"lw_pink1" : preload("res://materials/lw_pink1.tres"),
	"lw_pink1_pulse" : preload("res://materials/lw_pink1_pulse.tres"),
	"slw_pink1" : preload("res://materials/slw_pink1.tres"),
	"slw_pink1_pulse" : preload("res://materials/slw_pink1_pulse.tres"),
	#
	"lw_white1" : preload("res://materials/lw_white1.tres"),
	"slw_white1" : preload("res://materials/slw_white1.tres"),
	#
}
const LC_STYLES = {
	"blue" : {
		"body0" : MATERIALS["badguy_black1"],
		"body1" : MATERIALS["badguy_black1"],
		"wheelwells" : MATERIALS["lw_blue1"],
		"slwbase" :  MATERIALS["slw_blue1"],
		"slwpulse" :  MATERIALS["slw_blue1_pulse"],
		"lwbase" :  MATERIALS["lw_blue1"],
		"lwpulse" : MATERIALS["lw_blue1_pulse"],
		"lattice" :  MATERIALS["lw_blue1"],
	},
	"orange" : {
		"body0" : MATERIALS["badguy_black1"],
		"body1" : MATERIALS["badguy_black1"],
		"wheelwells" : MATERIALS["lw_orange1"],
		"slwbase" : MATERIALS["slw_orange1"],
		"slwpulse" : MATERIALS["slw_orange1_pulse"],
		"lwbase" : MATERIALS["lw_orange1"],
		"lwpulse" : MATERIALS["lw_orange1_pulse"],
		"lattice" : MATERIALS["lw_orange1"],
	},
	"yellow" : {
		"body0" : MATERIALS["badguy_black1"],
		"body1" : MATERIALS["badguy_black1"],
		"wheelwells" : MATERIALS["lw_yellow1"],
		"slwbase" : MATERIALS["slw_yellow1"],
		"slwpulse" : MATERIALS["slw_yellow1_pulse"],
		"lwbase" : MATERIALS["lw_yellow1"],
		"lwpulse" : MATERIALS["lw_yellow1_pulse"],
		"lattice" : MATERIALS["lw_yellow1"],
	},
	"green" : {
		"body0" : MATERIALS["badguy_black1"],
		"body1" : MATERIALS["badguy_black1"],
		"wheelwells" : MATERIALS["lw_green1"],
		"slwbase" : MATERIALS["slw_green1"],
		"slwpulse" : MATERIALS["slw_green1_pulse"],
		"lwbase" : MATERIALS["lw_green1"],
		"lwpulse" : MATERIALS["lw_green1_pulse"],
		"lattice" : MATERIALS["lw_green1"],
	},
	"pink" : {
		"body0" : MATERIALS["badguy_black1"],
		"body1" : MATERIALS["badguy_black1"],
		"wheelwells" : MATERIALS["lw_pink1"],
		"slwbase" : MATERIALS["slw_pink1"],
		"slwpulse" : MATERIALS["slw_pink1_pulse"],
		"lwbase" : MATERIALS["lw_pink1"],
		"lwpulse" : MATERIALS["lw_pink1_pulse"],
		"lattice" : MATERIALS["lw_pink1"],
	},
	"godwhite" : {
		"body0" : MATERIALS["father_white1"],
		"body1" : MATERIALS["badguy_black1"],
		"wheelwells" : MATERIALS["lw_white1"],
		"slwbase" : MATERIALS["slw_white1"],
		"slwpulse" : MATERIALS["slw_blue1_pulse"],
		"lwbase" : MATERIALS["lw_white1"],
		"lwpulse" : MATERIALS["lw_blue1_pulse"],
		"lattice" : MATERIALS["lw_white1"],
	},
}
const TANK_STYLES = {
	"orange" : {
		"body0" : MATERIALS["sdmg_badguy_black1"],
		"lattice" : MATERIALS["lw_orange1"],
		"turret" : MATERIALS["badguy_black1"],
		"barrel" : MATERIALS["badguy_black1"],
		"pit" : MATERIALS["lw_orange1"],
		"muzzle" : MATERIALS["lw_orange1"],
		"shot" : MATERIALS["lw_orange1"],
		"tracks" : MATERIALS["lw_orange1"],
		"upper_radar" : MATERIALS["radarup_slw_orange1"],
		"lower_radar" : MATERIALS["radarlo_slw_orange1"],
	},
	"blue" : {
		"body0" : MATERIALS["sdmg_badguy_black1"],
		"lattice" : MATERIALS["lw_blue1"],
		"turret" : MATERIALS["badguy_black1"],
		"barrel" : MATERIALS["badguy_black1"],
		"pit" : MATERIALS["lw_blue1"],
		"muzzle" : MATERIALS["lw_blue1"],
		"shot" : MATERIALS["lw_blue1"],
		"tracks" : MATERIALS["lw_blue1"],
		"upper_radar" : MATERIALS["radarup_slw_blue1"],
		"lower_radar" : MATERIALS["radarlo_slw_blue1"],
	},
	"green" : {
		"body0" : MATERIALS["sdmg_badguy_black1"],
		"lattice" : MATERIALS["lw_green1"],
		"turret" : MATERIALS["badguy_black1"],
		"barrel" : MATERIALS["badguy_black1"],
		"pit" : MATERIALS["lw_green1"],
		"muzzle" : MATERIALS["lw_green1"],
		"shot" : MATERIALS["lw_green1"],
		"tracks" : MATERIALS["lw_green1"],
		"upper_radar" : MATERIALS["radarup_slw_green1"],
		"lower_radar" : MATERIALS["radarlo_slw_green1"],
	},
}
