extends Node

const LC_MATERIALS = {
	"badguy_black1" : preload("res://materials/badguy_black1.tres"),
	"father_white1" : preload("res://materials/father_white1.tres"),
	"lw_blue1" : preload("res://materials/lw_blue1.tres"),
	"lw_blue1_pulse" : preload("res://materials/lw_blue1_pulse.tres"),
	"slw_blue1" : preload("res://materials/slw_blue1.tres"),
	"slw_blue1_pulse" : preload("res://materials/slw_blue1_pulse.tres"),
	"lw_orange1" : preload("res://materials/lw_orange1.tres"),
	"lw_orange1_pulse" : preload("res://materials/lw_orange1_pulse.tres"),
	"slw_orange1" : preload("res://materials/slw_orange1.tres"),
	"slw_orange1_pulse" : preload("res://materials/slw_orange1_pulse.tres"),
	"lw_yellow1" : preload("res://materials/lw_yellow1.tres"),
	"lw_yellow1_pulse" : preload("res://materials/lw_yellow1_pulse.tres"),
	"slw_yellow1" : preload("res://materials/slw_yellow1.tres"),
	"slw_yellow1_pulse" : preload("res://materials/slw_yellow1_pulse.tres"),
	"lw_green1" : preload("res://materials/lw_green1.tres"),
	"lw_green1_pulse" : preload("res://materials/lw_green1_pulse.tres"),
	"slw_green1" : preload("res://materials/slw_green1.tres"),
	"slw_green1_pulse" : preload("res://materials/slw_green1_pulse.tres"),
	"lw_pink1" : preload("res://materials/lw_pink1.tres"),
	"lw_pink1_pulse" : preload("res://materials/lw_pink1_pulse.tres"),
	"slw_pink1" : preload("res://materials/slw_pink1.tres"),
	"slw_pink1_pulse" : preload("res://materials/slw_pink1_pulse.tres"),
	#
	"lw_white1" : preload("res://materials/lw_white1.tres"),
	"slw_white1" : preload("res://materials/slw_white1.tres"),
	#
}
const LC_STYLES = {
	"blue" : {
		"body0" : LC_MATERIALS["badguy_black1"],
		"body1" : LC_MATERIALS["badguy_black1"],
		"wheelwells" : LC_MATERIALS["lw_blue1"],
		"slwbase" :  LC_MATERIALS["slw_blue1"],
		"slwpulse" :  LC_MATERIALS["slw_blue1_pulse"],
		"lwbase" :  LC_MATERIALS["lw_blue1"],
		"lwpulse" : LC_MATERIALS["lw_blue1_pulse"],
		"lattice" :  LC_MATERIALS["lw_blue1"],
	},
	"orange" : {
		"body0" : LC_MATERIALS["badguy_black1"],
		"body1" : LC_MATERIALS["badguy_black1"],
		"wheelwells" : LC_MATERIALS["lw_orange1"],
		"slwbase" : LC_MATERIALS["slw_orange1"],
		"slwpulse" : LC_MATERIALS["slw_orange1_pulse"],
		"lwbase" : LC_MATERIALS["lw_orange1"],
		"lwpulse" : LC_MATERIALS["lw_orange1_pulse"],
		"lattice" : LC_MATERIALS["lw_orange1"],
	},
	"yellow" : {
		"body0" : LC_MATERIALS["badguy_black1"],
		"body1" : LC_MATERIALS["badguy_black1"],
		"wheelwells" : LC_MATERIALS["lw_yellow1"],
		"slwbase" : LC_MATERIALS["slw_yellow1"],
		"slwpulse" : LC_MATERIALS["slw_yellow1_pulse"],
		"lwbase" : LC_MATERIALS["lw_yellow1"],
		"lwpulse" : LC_MATERIALS["lw_yellow1_pulse"],
		"lattice" : LC_MATERIALS["lw_yellow1"],
	},
	"green" : {
		"body0" : LC_MATERIALS["badguy_black1"],
		"body1" : LC_MATERIALS["badguy_black1"],
		"wheelwells" : LC_MATERIALS["lw_green1"],
		"slwbase" : LC_MATERIALS["slw_green1"],
		"slwpulse" : LC_MATERIALS["slw_green1_pulse"],
		"lwbase" : LC_MATERIALS["lw_green1"],
		"lwpulse" : LC_MATERIALS["lw_green1_pulse"],
		"lattice" : LC_MATERIALS["lw_green1"],
	},
	"pink" : {
		"body0" : LC_MATERIALS["badguy_black1"],
		"body1" : LC_MATERIALS["badguy_black1"],
		"wheelwells" : LC_MATERIALS["lw_pink1"],
		"slwbase" : LC_MATERIALS["slw_pink1"],
		"slwpulse" : LC_MATERIALS["slw_pink1_pulse"],
		"lwbase" : LC_MATERIALS["lw_pink1"],
		"lwpulse" : LC_MATERIALS["lw_pink1_pulse"],
		"lattice" : LC_MATERIALS["lw_pink1"],
	},
	"godwhite" : {
		"body0": LC_MATERIALS["father_white1"],
		"body1": LC_MATERIALS["badguy_black1"],
		"wheelwells" : LC_MATERIALS["lw_white1"],
		"slwbase" : LC_MATERIALS["slw_white1"],
		"slwpulse" : LC_MATERIALS["slw_blue1_pulse"],
		"lwbase" : LC_MATERIALS["lw_white1"],
		"lwpulse" : LC_MATERIALS["lw_blue1_pulse"],
		"lattice" : LC_MATERIALS["lw_white1"],
	},
}
