extends Node

const LC_MATERIALS = {
	#"body" : preload("res://materials/badguy_black1.tres"),
	"blue" : {
		"body0" : preload("res://materials/badguy_black1.tres"),
		"body1" : preload("res://materials/badguy_black1.tres"),
		"wheelwells" : preload("res://materials/lw_blue1.tres"),
		"slwbase" : preload("res://materials/slw_blue1.tres"),
		"slwpulse" : preload("res://materials/slw_blue1_pulse.tres"),
		"lwbase" : preload("res://materials/lw_blue1.tres"),
		"lwpulse" : preload("res://materials/lw_blue1_pulse.tres"),
		"lattice" : preload("res://materials/lw_blue1.tres"),
	},
	"orange" : {
		"body0" : preload("res://materials/badguy_black1.tres"),
		"body1" : preload("res://materials/badguy_black1.tres"),
		"wheelwells" : preload("res://materials/lw_orange1.tres"),
		"slwbase" : preload("res://materials/slw_orange1.tres"),
		"slwpulse" : preload("res://materials/slw_orange1_pulse.tres"),
		"lwbase" : preload("res://materials/lw_orange1.tres"),
		"lwpulse" : preload("res://materials/lw_orange1_pulse.tres"),
		"lattice" : preload("res://materials/lw_orange1.tres"),
	},
	"yellow" : {
		"body0" : preload("res://materials/badguy_black1.tres"),
		"body1" : preload("res://materials/badguy_black1.tres"),
		"wheelwells" : preload("res://materials/lw_yellow1.tres"),
		"slwbase" : preload("res://materials/slw_yellow1.tres"),
		"slwpulse" : preload("res://materials/slw_yellow1_pulse.tres"),
		"lwbase" : preload("res://materials/lw_yellow1.tres"),
		"lwpulse" : preload("res://materials/lw_yellow1_pulse.tres"),
		"lattice" : preload("res://materials/lw_yellow1.tres"),
	},
	"green" : {
		"body0" : preload("res://materials/badguy_black1.tres"),
		"body1" : preload("res://materials/badguy_black1.tres"),
		"wheelwells" : preload("res://materials/lw_green1.tres"),
		"slwbase" : preload("res://materials/slw_green1.tres"),
		"slwpulse" : preload("res://materials/slw_green1_pulse.tres"),
		"lwbase" : preload("res://materials/lw_green1.tres"),
		"lwpulse" : preload("res://materials/lw_green1_pulse.tres"),
		"lattice" : preload("res://materials/lw_green1.tres"),
	},
	"pink" : {
		"body0" : preload("res://materials/badguy_black1.tres"),
		"body1" : preload("res://materials/badguy_black1.tres"),
		"wheelwells" : preload("res://materials/lw_pink1.tres"),
		"slwbase" : preload("res://materials/slw_pink1.tres"),
		"slwpulse" : preload("res://materials/slw_pink1_pulse.tres"),
		"lwbase" : preload("res://materials/lw_pink1.tres"),
		"lwpulse" : preload("res://materials/lw_pink1_pulse.tres"),
		"lattice" : preload("res://materials/lw_pink1.tres"),
	},
	"godwhite" : {
		"body0": preload("res://materials/father_white1.tres"),
		"body1": preload("res://materials/badguy_black1.tres"),
		"wheelwells" : preload("res://materials/lw_white1.tres"),
		"slwbase" : preload("res://materials/slw_white1.tres"),
		"slwpulse" : preload("res://materials/slw_blue1_pulse.tres"),
		"lwbase" : preload("res://materials/lw_white1.tres"),
		"lwpulse" : preload("res://materials/lw_blue1_pulse.tres"),
		"lattice" : preload("res://materials/lw_white1.tres"),
	},
}
