extends Node

signal pause_toggled
signal player_spawned
signal player_just_fuckkin_died
signal ai_spawned
signal ai_just_fuckkin_died
signal player_became_targetable
signal player_became_untargetable
signal data_capsule_collected
